version: '3.9'
services:
  web:
    build: .
    command: bash -c "
            python /stripe_project/manage.py migrate
            && python /stripe_project/data_example.py
            && python /stripe_project/manage.py runserver 0.0.0.0:8000" 
    volumes:
      - .:/stripe_project
    environment:
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - DEBUG=${DEBUG}
      - POSTGRES_DB_NAME=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - STRIPE_PUBLIC_KEY=${STRIPE_PUBLIC_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:15
    build: 
      context: .
      dockerfile: Dockerfile.db
    ports: 
      - 8080:8080
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - "POSTGRES_HOST_AUTH_METHOD=trust"