version: '3.9'
services:
  web:
    build: .
    command: bash -c "
            python /stripe_project/manage.py migrate
            && python /stripe_project/data_example.py
            && python /stripe_project/manage.py runserver 0.0.0.0:8000" 
    volumes:
      - .:/stripe_project
    environment:
      - SECRET_KEY=django-insecure-pbco8+91^nssfe^ddw=xc#%-y!)u1@w&&b$g1r#6viu=)nh+y3
      - DEBUG=False
      - POSTGRES_DB_NAME=${POSTGRES_DB}
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=5432
      - STRIPE_PUBLIC_KEY=pk_test_51M7GxwICkydFAOAD1hI570eBxaDChoc1GwefBGEYrxdVrCZiuCkMJ6EvcSpSyMNRIJQVYlXCkBjwZZF11WviZjLt00zFVoZ6gR
      - STRIPE_SECRET_KEY=sk_test_51M7GxwICkydFAOADxW2iWF6XCs1Kz84jg5R9EQcod8bISUZCUgttcOEjXftOZCbCCqmeqEZzEE7LqHxGACjxwpuL00J8rYgwsY
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:15
    build: 
      context: .
      dockerfile: Dockerfile.db
    # volumes:
    #   - /postgres_data:/var/lib/postgresql/data/
    ports: 
      - 8080:8080
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - "POSTGRES_HOST_AUTH_METHOD=trust"