# Generated by Django 4.1.3 on 2022-11-25 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_formed',
        ),
    ]
